In [1]:
import pandas as pd
from sqlalchemy import text
from sqlalchemy import create_engine
from pathlib import Path
import pandas as pd
import numpy as np
import re
import os

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.default = "plotly_mimetype+notebook"

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

function for extracting data from mysql database.

In [ ]:
def extract_queries(sql_content: str) -> dict:
    '''
    从 SQL 文件内容中提取所有 -- name: xxx 标记的查询
    '''
    queries = {}
    current_name = None
    current_lines = []

    for line in sql_content.splitlines():
        # matching pattern: `-- name:`  (allow blanks at the front and end)
        match = re.match(r'^\s*--\s*name:\s*(.+?)\s*$', line, re.IGNORECASE)
        
        if match:
            # save previous one matching query 
            if current_name is not None:
                queries[current_name] = '\n'.join(current_lines).strip()
            # setup for matching query
            current_name = match.group(1).strip() # split '-- name: ...'
            current_lines = []
        else:
            if current_name is not None:
                current_lines.append(line)

    # save the last query
    if current_name is not None:
        queries[current_name] = '\n'.join(current_lines).strip()

    return queries


def query_from_file(sql_path, query_name, database_name):
    '''
    sql path: sql file path
    query_name: the part after '-- name:'
    database_name: mysql database name
    return pd df
    '''
    engine = create_engine(f'mysql+pymysql://root:Fu2002219219@localhost:3306/{database_name}')
    
    content = Path(sql_path).read_text(encoding='utf-8')
    queries = extract_queries(content)

    if query_name not in queries.keys():
        raise ValueError(f"{query_name} does not exist, avaliable queries: {list(queries.keys())}")

    else:
        sql = pd.read_sql(text(queries[query_name]), engine)


    return sql


parent_dir = os.path.dirname(os.getcwd())

In [4]:
query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'test',
                'cosmetics_shop_data'
)

,event_time,event_type,product_id,brand,price,user_id,user_session,category_id
0,2019-10-01 00:00:00,cart,5773203,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,1487580005134238553
1,2019-10-01 00:00:03,cart,5773353,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,1487580005134238553
2,2019-10-01 00:00:07,cart,5723490,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885,1487580005134238553
3,2019-10-01 00:00:07,cart,5881589,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,2151191071051219817
4,2019-10-01 00:00:15,cart,5881449,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9,1487580013522845895
...,...,...,...,...,...,...,...,...
19583737,2020-02-29 23:59:32,view,5885416,grattol,6.27,622082947,fb29909b-6ef5-4662-b4ee-288e73e5dc10,1487580005092295511
19583738,2020-02-29 23:59:39,cart,5550686,None,1.11,459705611,05d2add3-01f7-47ee-8364-27341673227f,1487580008145748965
19583739,2020-02-29 23:59:45,view,5850628,grattol,5.24,622090043,ab7d349f-db5d-4790-8ab1-31e5c894459d,1602943681873052386
19583740,2020-02-29 23:59:54,view,5716351,irisk,0.79,619841242,18af673b-7fb9-4202-a66d-5c855bc0fd2d,1487580010872045658
19583741,2020-02-29 23:59:59,view,5927709,de.lux,3.17,621669991,daa3c677-5360-4327-847e-d29658716b99,1487580013950664926

In [5]:
query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'test_1',
                'cosmetics_shop_data'
)

,event_time,event_type,product_id,brand,price,user_id,user_session,category_id
0,2019-10-01 02:05:17,view,5892084,None,0.0,555458569,c048be2f-547d-4add-9bc6-09aa1e7ae9de,1597770225539875791
1,2019-10-01 02:15:41,view,5892052,None,0.0,555455025,320f6021-30ac-4a58-ae17-bac1cc32aac3,1487580010377117763
2,2019-10-01 04:25:00,view,5873432,None,0.0,500054739,701220b4-45b4-4028-bcc3-5d77480253ff,2007399943458784057
3,2019-10-01 04:33:15,view,5882605,None,0.0,523154930,caaf1f68-7b97-4d27-9c3d-8b28c2920ffd,1487580013522845895
4,2019-10-01 05:16:30,view,5889621,None,0.0,523988665,00849bd2-fcd2-4cb4-af31-4e264f151848,1487580010561667147
...,...,...,...,...,...,...,...,...
86321,2020-02-29 23:11:45,remove_from_cart,5779241,None,0.0,505509170,e9112cd7-bfe2-2810-36d7-d4cc9f6253e7,1487580004916134735
86322,2020-02-29 23:11:45,remove_from_cart,5848387,None,0.0,505509170,e9112cd7-bfe2-2810-36d7-d4cc9f6253e7,1752742615205281895
86323,2020-02-29 23:23:16,view,5932595,None,0.0,562215508,4781b9a0-38dc-41c0-a2c4-7ee9fbcd4536,1487580013950664926
86324,2020-02-29 23:35:37,view,5932595,None,0.0,361231992,f267a62e-63d2-4864-881b-83c087a93ca4,1487580013950664926
86325,2020-02-29 23:42:23,view,5932595,None,0.0,544088304,654b3f83-1900-43f8-994e-c3a6e885085d,1487580013950664926

remove null `user_session`, `session_id` that map to multi users and `session_id` that spam over a day.

remove rows having price <= 0.

how active were people on the platform?

- MAU (active counted as having at least one session)

- how frequently user visit the platform monthly?
    - average seesions/user, monthly
    - single or mutli sessions (can break down deeper) in a month, each of their portion
    - for users having multi sessions in a month, avg time difference (try date unit first) between sessions; first aggregate each user's avg time difference between sessions, then take average across users in the month
    - active days (have at least 1 session in a day) / user, monthly
 
- how users engage with the products on the platfrom?
    - average views / user, average add_carts / user, average purchases / user,  monthly
    - average number of product categories viewd/added cart/purchased per user, monthly
    - average number of product price tier viewd/added cart/purchased per user, monthly
    - average number of actions / session, monthly
    - average number of product categories interacted with / session, monthly

- how the platform retaining user?
    - user last month active, this month still active?
        - any of view, cart and puarchase happened last month, and have seesion record this month users / this month's total user
        - any of view, cart and puarchase happened last month, and have seesion record this month users / last month's total user