In [1]:
import pandas as pd
from sqlalchemy import text
from sqlalchemy import create_engine
from pathlib import Path
import pandas as pd
import numpy as np
import re
import os

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.default = "plotly_mimetype+notebook"

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

function for extracting data from mysql database.

In [2]:
def extract_queries(sql_content: str) -> dict:
    '''
    从 SQL 文件内容中提取所有 -- name: xxx 标记的查询
    '''
    queries = {}
    current_name = None
    current_lines = []

    for line in sql_content.splitlines():
        # matching pattern: `-- name:`  (allow blanks at the front and end)
        match = re.match(r'^\s*--\s*name:\s*(.+?)\s*$', line, re.IGNORECASE)
        
        if match:
            # save previous one matching query 
            if current_name is not None:
                queries[current_name] = '\n'.join(current_lines).strip()
            # setup for matching query
            current_name = match.group(1).strip() # split '-- name: ...'
            current_lines = []
        else:
            if current_name is not None:
                current_lines.append(line)

    # save the last query
    if current_name is not None:
        queries[current_name] = '\n'.join(current_lines).strip()

    return queries


def query_from_file(sql_path, query_name, database_name):
    '''
    sql path: sql file path
    query_name: the part after '-- name:'
    database_name: mysql database name
    return pd df
    '''
    engine = create_engine(f'mysql+pymysql://root:Fu2002219219@localhost:3306/{database_name}')
    
    content = Path(sql_path).read_text(encoding='utf-8')
    queries = extract_queries(content)

    if query_name not in queries.keys():
        raise ValueError(f"{query_name} does not exist, avaliable queries: {list(queries.keys())}")

    else:
        sql = pd.read_sql(text(queries[query_name]), engine)


    return sql


parent_dir = os.path.dirname(os.getcwd())

remove null `user_session`, `session_id` that map to multi users and `session_id` that spam over a day.

remove rows having price <= 0.

how active were people on the platform?

- MAU (active counted as having at least one session)

- how frequently user visit the platform monthly?
    - average seesions/user, monthly
    - single or mutli sessions (can break down deeper) in a month, each of their portion
    - for users having multi sessions in a month, avg time difference (try date unit first) between sessions; first aggregate each user's avg time difference between sessions, then take average across users in the month
    - active days (have at least 1 session in a day) / user, monthly
 
- how users engage with the products on the platfrom?
    - average views / user, average add_carts / user, average purchases / user,  monthly
    - average number of product categories viewd/added cart/purchased per user, monthly
    - average number of product price tier viewd/added cart/purchased per user, monthly
    - average number of actions / session, monthly
    - average number of product categories interacted with / session, monthly

- how the platform retaining user?
    - user last month active, this month still active?
        - any of view, cart and puarchase happened last month, and have seesion record this month users / this month's total user
        - any of view, cart and puarchase happened last month, and have seesion record this month users / last month's total user

In [ ]:
df = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '01. monthly user activity',
                'cosmetics_shop_data'
)

df['active_group'] = np.select(
    [df['active_days'] == 1, df['active_days'] == 2, df['active_days'] == 3, df['active_days']>= 4],
    ['1_day_active', '2_days_active', '3_days_active', 'more_than_3_days_active'], default='none'
)

In [88]:
df_1 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '02. monthly session activity',
                'cosmetics_shop_data'
)

In [ ]:
df_2 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '03. monthly active users',
                'cosmetics_shop_data'
)

df_3 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '04. average sessions per user monthly',
                'cosmetics_shop_data'
)

df_4 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '05. single versus multiple sessions monthly',
                'cosmetics_shop_data'
)

df_5 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '06. detailed monthly session frequency distribution',
                'cosmetics_shop_data'
)

df_6 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '07. average gap between sessions for multi-session users monthly',
                'cosmetics_shop_data'
)

df_7 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '08. average active days per user monthly',
                'cosmetics_shop_data'
)

df_8 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'monthly total revenue',
                'cosmetics_shop_data'
)

In [136]:
subplot = make_subplots(rows = 3, cols=3,
                        subplot_titles=['MAU', 'Average sessions/user', 'Single/Multi session user rate', 'Single/Multi session user rate (break down)',
                                        'session gap (day)/user', 'Average active days/user', 'Active days group', 'GMV'
                                        ]
                        )

fig = px.bar(df_2, x='month_start', y = 'mau')
fig_1 = px.bar(df_3, x='month_start', y = 'avg_sessions_per_user')
fig_2 = px.bar(df_4.iloc[:, [0,4,5]].melt(id_vars='month_start'), x='month_start', y='value', color='variable', barmode='stack')
fig_3 = px.bar(df_5, x='month_start', y='user_share', color ='session_segment', barmode='stack')
fig_4 = px.bar(df_6, x='month_start', y='avg_gap_days')
fig_5 = px.bar(df_7, x='month_start', y='avg_active_days_per_user')

df_agg = df.groupby(['month_start', 'active_group'])['user_id'].agg(['count']).reset_index()
df_agg_1 = df_agg.groupby('month_start').agg('sum').reset_index()
df_agg = pd.merge(df_agg, df_agg_1.rename(columns={'count': 'month_total'}).iloc[:, [0,2]], on='month_start', how = 'inner')
df_agg['group_portion'] = df_agg['count'] / df_agg['month_total']
fig_6 = px.bar(df_agg, x='month_start', y='group_portion', color='active_group', barmode='stack')

fig_7 = px.line(data_frame=df_8, x='month_start', y='total_revenue')
fig_7.update_traces(fill = 'tozeroy', fillcolor="rgba(99, 110, 250, 0.45)")

for trace in fig.data:
    subplot.add_trace(trace, row = 1, col = 1)
    subplot.update_yaxes(range =[200_000, np.inf], row =1 , col=1)
    subplot.update_layout(template ='plotly_white')

for trace in fig_1.data:
    subplot.add_trace(trace, row = 1, col = 2)
    subplot.update_yaxes(range =[1, np.inf], row =1 , col=2)
    subplot.update_layout(template ='plotly_white')

for trace in fig_2.data:
    subplot.add_trace(trace, row = 1, col = 3)
    subplot.update_layout(template ='plotly_white')

for trace in fig_3.data:
    subplot.add_trace(trace, row = 2, col = 1)
    subplot.update_layout(template ='plotly_white')

for trace in fig_4.data:
    subplot.add_trace(trace, row = 2, col = 2)
    subplot.update_yaxes(range =[1.5, np.inf], row =2 , col=2)
    subplot.update_layout(template ='plotly_white')

for trace in fig_5.data:
    subplot.add_trace(trace, row = 2, col = 3)
    subplot.update_yaxes(range =[1, np.inf], row =2 , col=3)
    subplot.update_layout(template ='plotly_white')

for trace in fig_6.data:
    subplot.add_trace(trace, row = 3, col = 1)
    subplot.update_layout(template ='plotly_white')

for trace in fig_7.data:
    subplot.add_trace(trace, row = 3, col = 2)
    subplot.update_layout(template ='plotly_white')
    subplot.update_yaxes(range =[75_000_0, np.inf], row =3 , col=2)
    

subplot.update_xaxes(type = 'category')
subplot.update_layout(height = 800, width = 1100, barmode = 'stack')
subplot.show()

In [138]:
df = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'monthly user activity link to is_buyer',
                'cosmetics_shop_data'
)

df['active_group'] = np.select(
    [df['active_days'] == 1, df['active_days'] == 2, df['active_days'] == 3, df['active_days']>= 4],
    ['1_day_active', '2_days_active', '3_days_active', 'more_than_3_days_active'], default='none'
)

In [139]:
df_agg = df.groupby(['month_start', 'active_group']).agg({
    'user_id': 'count',
    'is_buyer': 'sum'
}).reset_index().rename(columns={'user_id': "total_base"})
df_agg['buyer_rate'] = df_agg['is_buyer'] / df_agg['total_base']
df_agg.query('month_start == "2019-11-01"')

  month_start             active_group  total_base  is_buyer  buyer_rate
4  2019-11-01             1_day_active      287883     12223    0.042458
5  2019-11-01            2_days_active       43758      6327    0.144591
6  2019-11-01            3_days_active       14769      3723    0.252082
7  2019-11-01  more_than_3_days_active       18671      8327    0.445986

In [140]:
df_agg

   month_start             active_group  total_base  is_buyer  buyer_rate
0   2019-10-01             1_day_active      328870     10494    0.031909
1   2019-10-01            2_days_active       39485      5235    0.132582
2   2019-10-01            3_days_active       13023      3086    0.236965
3   2019-10-01  more_than_3_days_active       15315      6023    0.393275
4   2019-11-01             1_day_active      287883     12223    0.042458
5   2019-11-01            2_days_active       43758      6327    0.144591
6   2019-11-01            3_days_active       14769      3723    0.252082
7   2019-11-01  more_than_3_days_active       18671      8327    0.445986
8   2019-12-01             1_day_active      294627     10904    0.037010
9   2019-12-01            2_days_active       43355      5424    0.125107
10  2019-12-01            3_days_active       13655      2995    0.219334
11  2019-12-01  more_than_3_days_active       15382      5683    0.369458
12  2020-01-01             1_day_active      321835     11200    0.034800
13  2020-01-01            2_days_active       49965      5649    0.113059
14  2020-01-01            3_days_active       16130      3452    0.214011
15  2020-01-01  more_than_3_days_active       18713      7064    0.377492
16  2020-02-01             1_day_active      307544     10431    0.033917
17  2020-02-01            2_days_active       46599      5279    0.113286
18  2020-02-01            3_days_active       15386      3065    0.199207
19  2020-02-01  more_than_3_days_active       17801      6397    0.359362

In [135]:
df_agg.pivot(index= 'month_start', columns= 'active_group')

               total_base                                                      \
active_group 1_day_active 2_days_active 3_days_active more_than_3_days_active
month_start
2019-10-01         399253         67582         28449                   45513
2019-11-01         372002         79337         33799                   58565
2019-12-01         385281         79601         31897                   48301
2020-01-01         412884         87111         35257                   55236
2020-02-01         386168         76782         31430                   47348

                 is_buyer                                                      \
active_group 1_day_active 2_days_active 3_days_active more_than_3_days_active
month_start
2019-10-01          20663         10861          6752                   15806
2019-11-01          23064         12591          7792                   20126
2019-12-01          23507         12573          7189                   16364
2020-01-01          23240         12494          7684                   18438
2020-02-01          21956         11315          6964                   16591

               buyer_rate
active_group 1_day_active 2_days_active 3_days_active more_than_3_days_active
month_start
2019-10-01       0.051754      0.160708      0.237337                0.347285
2019-11-01       0.062000      0.158703      0.230539                0.343652
2019-12-01       0.061013      0.157950      0.225382                0.338792
2020-01-01       0.056287      0.143426      0.217943                0.333804
2020-02-01       0.056856      0.147365      0.221572                0.350406

In [56]:
df_9 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '09. average views carts purchases per user monthly',
                'cosmetics_shop_data'
)

df_10 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '10. average distinct categories per user monthly',
                'cosmetics_shop_data'
)

df_11 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '11. average actions per session monthly',
                'cosmetics_shop_data'
)

df_12 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '12. average distinct categories interacted per session monthly',
                'cosmetics_shop_data'
)

In [137]:
fig = px.bar(df_9, x= 'month_start', y= ['avg_views_per_user',
       'avg_add_carts_per_user', 'avg_purchases_per_user'], barmode='group')
fig_1 = px.bar(df_10, x= 'month_start', y= ['avg_categories_viewed_per_user',
       'avg_categories_added_cart_per_user', 'avg_categories_purchased_per_user'], barmode='group')

fig_2 = px.bar(df_11, x= 'month_start', y= 'avg_actions_per_session')
fig_3 = px.bar(df_12, x= 'month_start', y= 'avg_categories_per_session')

subplot = make_subplots(rows=2, cols=2, subplot_titles=['average views/carts/purchases', 'average viewd/carted/purchased categories',
                                                        'average actions/session', 'average categories interacted/session'
                                                        ])

for trace in fig.data:
    subplot.add_trace(trace, row = 1, col = 1)
    subplot.update_layout(template = 'plotly_white')

for trace in fig_1.data:
    subplot.add_trace(trace, row = 1, col = 2)
    subplot.update_layout(template = 'plotly_white')

for trace in fig_2.data:
    subplot.add_trace(trace, row = 2, col = 1)
    subplot.update_layout(template = 'plotly_white')

for trace in fig_3.data:
    subplot.add_trace(trace, row = 2, col = 2)
    subplot.update_layout(template = 'plotly_white')

subplot.update_xaxes(type = 'category')
subplot.update_layout(height = 600, width = 1000)
subplot.show()