In [1]:
# import relevant libaries
import pandas as pd
from sqlalchemy import text
from sqlalchemy import create_engine
from pathlib import Path
import pandas as pd
import numpy as np
import re
import os

import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
pio.renderers.default = "plotly_mimetype+notebook"

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

All source data are stored in Mysql database, and will be queried and pulled using Mysql statement based on analysis needs.   

Function for extracting data from Mysql database.

In [2]:
def extract_queries(sql_content: str) -> dict:
    '''
    read .sql content, each complete query follows the comment pattern: -- name: xxx 
    '''
    queries = {}
    current_name = None
    current_lines = []

    for line in sql_content.splitlines():
        # matching pattern: `-- name:`  (allow blanks at the front and end)
        match = re.match(r'^\s*--\s*name:\s*(.+?)\s*$', line, re.IGNORECASE)
        
        if match:
            # save previous one matching query 
            if current_name is not None:
                queries[current_name] = '\n'.join(current_lines).strip()
            # setup for matching query
            current_name = match.group(1).strip() # split '-- name: ...'
            current_lines = []
        else:
            if current_name is not None:
                current_lines.append(line)

    # save the last query
    if current_name is not None:
        queries[current_name] = '\n'.join(current_lines).strip()

    return queries


def query_from_file(sql_path, query_name, database_name):
    '''
    sql path: sql file path
    query_name: the part after '-- name:'
    database_name: mysql database name
    return pd df
    '''
    engine = create_engine(f'mysql+pymysql://root:Fu2002219219@localhost:3306/{database_name}')
    
    content = Path(sql_path).read_text(encoding='utf-8')
    queries = extract_queries(content)

    if query_name not in queries.keys():
        raise ValueError(f"{query_name} does not exist, avaliable queries: {list(queries.keys())}")

    else:
        sql = pd.read_sql(text(queries[query_name]), engine)


    return sql


parent_dir = os.path.dirname(os.getcwd())

Start with getting to know how users are like on this pltaform by asking **how active are users on the platform monthly?** 

Before pulling the data, since `user_session` attribute will be used and 2.22% Na rate detected in the column during our profiling process, other issues that contradict to the real user browsing facts are 1 user session maps to multiple users and 1 user session lasts for over a day, so more data preparation is taken:  

- remove null `user_session`, `session_id` that map to multi users and `session_id` that spam over a day.
- remove rows having price <= 0.

Then breaking down the main problem of our interest as follows:  

- MAU (active counted as having at least one session in a month)

- how frequently user visit the platform in a month?
    - average seesions/user, monthly
    - single or mutli sessions (can further segment) in a month, each of their portion
    - for users having multi sessions in a month, avg time difference (measured in date unit) between sessions; first aggregate each user's avg time difference between sessions, then take average across users in the month
    - active days (have at least 1 session in a day) / user, monthly
 
- how users engage with the products on the platfrom?
    - average views / user, average add_carts / user, average purchases / user,  monthly
    - average number of product categories viewd/added cart/purchased per user, monthly
    - average number of actions / session, monthly
    - average number of product categories interacted with / session, monthly

- how the platform is retaining user?
    - user last month active, this month still active?
        - any of view, cart and puarchase happened last month, and have seesion record this month users / this month's total user
        - any of view, cart and puarchase happened last month, and have seesion record this month users / last month's total user

In [55]:
# pull relevant dataframes from the database
df = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'monthly user activity link to is_buyer',
                'cosmetics_shop_data'
)

df['active_group'] = np.select(
    [df['active_days'] == 1, df['active_days'] == 2, df['active_days'] == 3, df['active_days']>= 4],
    ['1_day_active', '2_days_active', '3_days_active', 'more_than_3_days_active'], default='none'
)

df_1 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '02. monthly session activity',
                'cosmetics_shop_data'
)

df_2 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '03. monthly active users',
                'cosmetics_shop_data'
)

df_3 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '04. average sessions per user monthly',
                'cosmetics_shop_data'
)

df_4 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '05. single versus multiple sessions monthly',
                'cosmetics_shop_data'
)

df_5 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '06. detailed monthly session frequency distribution',
                'cosmetics_shop_data'
)

df_6 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '07. average gap between sessions for multi-session users monthly',
                'cosmetics_shop_data'
)

df_7 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '08. average active days per user monthly',
                'cosmetics_shop_data'
)

df_8 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'monthly total revenue',
                'cosmetics_shop_data'
)

Nov. showed a revenue peak among the 5 months, the pattern in which Nov.'s noticeable higher average sessions per user, active days per user but less monthly active users leads to a possible explanation that user being more active on the platform played a critical role in boosting Nov.'s total revenue.

In [63]:
subplot = make_subplots(rows = 3, cols=3,
                        subplot_titles=['MAU', 'Average sessions/user', 'Single/Multi sessions user rate', 'Single/Multi sessions user rate (further break down)',
                                        'session gap (day)/user', 'Average active days/user', 'Active days group', 'GMV'
                                        ]
                        )

fig = px.bar(df_2, x='month_start', y = 'mau')
fig_1 = px.bar(df_3, x='month_start', y = 'avg_sessions_per_user')
fig_2 = px.bar(df_4.iloc[:, [0,4,5]].melt(id_vars='month_start'), x='month_start', y='value', color='variable', barmode='stack')
fig_3 = px.bar(df_5, x='month_start', y='user_share', color ='session_segment', barmode='stack')
fig_4 = px.bar(df_6, x='month_start', y='avg_gap_days')
fig_5 = px.bar(df_7, x='month_start', y='avg_active_days_per_user')

df_agg = df.groupby(['month_start', 'active_group'])['user_id'].agg(['count']).reset_index()
df_agg_1 = df_agg.groupby('month_start').agg('sum').reset_index()
df_agg = pd.merge(df_agg, df_agg_1.rename(columns={'count': 'month_total'}).iloc[:, [0,2]], on='month_start', how = 'inner')
df_agg['group_portion'] = df_agg['count'] / df_agg['month_total']
fig_6 = px.bar(df_agg, x='month_start', y='group_portion', color='active_group', barmode='stack')

fig_7 = px.line(df_8, x='month_start', y='total_revenue')
fig_7.update_traces(fill = 'tozeroy', fillcolor="rgba(99, 110, 250, 0.45)")

for trace in fig.data:
    subplot.add_trace(trace, row = 1, col = 1)
    subplot.update_yaxes(range =[200_000, np.inf], row =1 , col=1)
    subplot.update_layout(template ='plotly_white')

for trace in fig_1.data:
    subplot.add_trace(trace, row = 1, col = 2)
    subplot.update_yaxes(range =[1, np.inf], row =1 , col=2)
    subplot.update_layout(template ='plotly_white', xaxis_title ='Month')

for trace in fig_2.data:
    subplot.add_trace(trace, row = 1, col = 3)
    subplot.update_layout(template ='plotly_white', xaxis_title ='Month')

for trace in fig_3.data:
    subplot.add_trace(trace, row = 2, col = 1)
    subplot.update_layout(template ='plotly_white', xaxis_title ='Month')

for trace in fig_4.data:
    subplot.add_trace(trace, row = 2, col = 2)
    subplot.update_yaxes(range =[1.5, np.inf], row =2 , col=2)
    subplot.update_layout(template ='plotly_white', xaxis_title ='Month')

for trace in fig_5.data:
    subplot.add_trace(trace, row = 2, col = 3)
    subplot.update_yaxes(range =[1, np.inf], row =2 , col=3)
    subplot.update_layout(template ='plotly_white', xaxis_title ='Month')

for trace in fig_6.data:
    subplot.add_trace(trace, row = 3, col = 1)
    subplot.update_layout(template ='plotly_white', xaxis_title ='Month')

for trace in fig_7.data:
    subplot.add_trace(trace, row = 3, col = 2)
    subplot.update_layout(template ='plotly_white', xaxis_title ='Month')
    subplot.update_yaxes(range =[75_000_0, np.inf], row =3 , col=2)
    
months = df_2['month_start'].drop_duplicates().sort_values()
subplot.update_xaxes(type = 'category', tickmode = 'array', tickvals = months.tolist(), ticktext=pd.to_datetime(months).dt.strftime('%Y-%m').tolist())
subplot.update_layout(height = 800, width = 1300, barmode = 'stack', title = 'How frequently users visit the platform in a month?')
subplot.show()

In [114]:
df_9 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '09. average views carts purchases per user monthly',
                'cosmetics_shop_data'
)

df_10 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '10. average distinct categories per user monthly',
                'cosmetics_shop_data'
)

df_11 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '11. average actions per session monthly',
                'cosmetics_shop_data'
)

df_12 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '12. average distinct categories interacted per session monthly',
                'cosmetics_shop_data'
)

In [116]:
fig = px.bar(df_9, x= 'month_start', y= ['avg_views_per_user',
       'avg_add_carts_per_user', 'avg_purchases_per_user'], barmode='group')
fig_1 = px.bar(df_10, x= 'month_start', y= ['avg_categories_viewed_per_user',
       'avg_categories_added_cart_per_user', 'avg_categories_purchased_per_user'], barmode='group')

fig_2 = px.bar(df_11, x= 'month_start', y= 'avg_actions_per_session')
fig_3 = px.bar(df_12, x= 'month_start', y= 'avg_categories_per_session')

subplot = make_subplots(rows=2, cols=2, subplot_titles=['average views/carts/purchases', 'average viewd/carted/purchased categories',
                                                        'average actions/session', 'average categories interacted/session'
                                                        ])

for trace in fig.data:
    subplot.add_trace(trace, row = 1, col = 1)
    subplot.update_layout(template = 'plotly_white')

for trace in fig_1.data:
    subplot.add_trace(trace, row = 1, col = 2)
    subplot.update_layout(template = 'plotly_white')

for trace in fig_2.data:
    subplot.add_trace(trace, row = 2, col = 1)
    subplot.update_layout(template = 'plotly_white')
    subplot.update_yaxes(range =[1, np.inf], row =2 , col=1)

for trace in fig_3.data:
    subplot.add_trace(trace, row = 2, col = 2)
    subplot.update_layout(template = 'plotly_white')
    subplot.update_yaxes(range =[0.5, np.inf], row =2 , col=2)

subplot.update_xaxes(type = 'category')
subplot.update_layout(height = 600, width = 1000, title = 'How users engage with the products on the platfrom?')
subplot.show()

To identify whether the pattern observed is precise, we need to narrow down its scope step by step.  

Oct. will be chosen for month on month comparison reference. First, breaking down monthly revenue through
$$
\text{GMV} = \text{MAU} \times \text{buyer conversion} \times \text{value/buyer}
$$

to identify which arithmetic component was effecting Nov's revenue the most.

In [9]:
df_gmv = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '11 metrics',
                'cosmetics_shop_data'
)

df_gmv_part = df_gmv.iloc[:2, [0,1,3,4]].transpose()
df_gmv_part.columns = df_gmv_part.iloc[0]
df_gmv_part = df_gmv_part.iloc[1:, :4]
df_gmv_part['mom'] = df_gmv_part['2019-11-01'] / df_gmv_part['2019-10-01'] - 1
#df_gmv_part['mom contribution'] = df_gmv_part['mom'] / (df_gmv_part['mom']).sum()
df_gmv_part.transpose()

                  mau buyer_conversion gmv_per_buyer
month_start
2019-10-01     396693           0.0626     46.372854
2019-11-01     365081           0.0838     47.985117
mom         -0.079689         0.338658      0.034767

33.87% of Nov.'s MoM buyer conversion significantly higher than the other components indicates the highest investigating priority.

Is user's monthly total active days increasing the monthly revenue?

- segment the monthly user base into 4 groups: 1 day total active (`1_day_active`), 2 days total active (`2_days_active`), 3 days total active (`3_days_active`), more than 3 days total active (`more_than_3_days_active`)

- Is the conversion lift (Nov. vs. Oct.) mainly attributed to the user group structure shifting or to each group's own conversion lift?

In [3]:
df = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'monthly user activity link to is_buyer',
                'cosmetics_shop_data'
)

In [7]:
df_agg = df.groupby(['month_start', 'active_group']).agg({
    'user_id': 'count',
    'is_buyer': 'sum'
}).reset_index().rename(columns={'user_id': "total_base"})
df_agg['buyer_rate'] = df_agg['is_buyer'] / df_agg['total_base']

df_oct = df_agg.query('month_start == "2019-10-01"').copy()
df_oct['portion_weight'] = df_oct['total_base'] / df_oct['total_base'].sum()
df_oct = df_oct.reset_index().iloc[:, 1:]

df_nov = df_agg.query('month_start == "2019-11-01"').copy()
df_nov['portion_weight'] = df_nov['total_base'] / df_nov['total_base'].sum()
df_nov = df_nov.reset_index().iloc[:, 1:]

In [8]:
def show_decimal_to_percentage(num, round_decimal_point):
    return str(np.round(num * 100, round_decimal_point)) + "%"

print('Oct. vs. Nov. buyer conversion: \n')
oct_conv = df.query('month_start == "2019-10-01"')['is_buyer'].sum() / len(df.query('month_start == "2019-10-01"'))
print('Oct. conversion: ', show_decimal_to_percentage(oct_conv, 3))
nov_conv = df.query('month_start == "2019-11-01"')['is_buyer'].sum() / len(df.query('month_start == "2019-11-01"'))
print('Nov. conversion: ', show_decimal_to_percentage(nov_conv, 3))
print("11. vs. 10. actual conversion lift: ", show_decimal_to_percentage(
    nov_conv - oct_conv, 3))
print("11. user group structure shifting effect: ", show_decimal_to_percentage(
    (df_nov['portion_weight'] * df_oct['buyer_rate']).sum() - oct_conv, 3
))
print("Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain: ", show_decimal_to_percentage(
    ((df_nov['portion_weight'] * df_oct['buyer_rate']).sum() - oct_conv)/(nov_conv - oct_conv), 3
))
print("11. user group conversion lift effect can explain: ", show_decimal_to_percentage(
    1 - ( (df_nov['portion_weight'] * df_oct['buyer_rate']).sum() - oct_conv)/(nov_conv - oct_conv), 3
))

Oct. vs. Nov. buyer conversion:

Oct. conversion:  6.261%
Nov. conversion:  8.382%
11. vs. 10. actual conversion lift:  2.12%
11. user group structure shifting effect:  0.814%
Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain:  38.385%
11. user group conversion lift effect can explain:  61.615%

11. user group structure shifting accounted for 38.39%, the main contribution came from the conversion lift within each user group.

In [9]:
df_pivot = pd.merge(df_nov.iloc[:, 1:], df_oct.iloc[:, 1:], on = 'active_group', how='inner', suffixes=('_nov', '_oct')).set_index('active_group')
df_pivot

,total_base_nov,is_buyer_nov,buyer_rate_nov,portion_weight_nov,total_base_oct,is_buyer_oct,buyer_rate_oct,portion_weight_oct
active_group,,,,,,,,
1_day_active,287883,12223,0.042458,0.788546,328870,10494,0.031909,0.829029
2_days_active,43758,6327,0.144591,0.119858,39485,5235,0.132582,0.099535
3_days_active,14769,3723,0.252082,0.040454,13023,3086,0.236965,0.032829
more_than_3_days_active,18671,8327,0.445986,0.051142,15315,6023,0.393275,0.038607

In [13]:
print('11. vs. 10. each group\'s conversion lift contribution: ')
print('each group\'s actucal conversion lift: ','\n', (df_pivot['buyer_rate_nov'] - df_pivot['buyer_rate_oct']).map(lambda x: show_decimal_to_percentage(x, 3)))

print('')
print('each group\'s conversion lift mom: ','\n', (df_pivot['buyer_rate_nov'] / df_pivot['buyer_rate_oct'] - 1).map(lambda x: show_decimal_to_percentage(x, 3)))

print('')
weighted_sum = (df_pivot['portion_weight_nov'] *(df_pivot['buyer_rate_nov'] - df_pivot['buyer_rate_oct'])).sum()
print('overall buyer conversion lift contribution: \n',
    (df_pivot['portion_weight_nov'] *(df_pivot['buyer_rate_nov'] - df_pivot['buyer_rate_oct']) / weighted_sum).map(lambda x: show_decimal_to_percentage(x, 3))
)

#print('\n1 day active group conversion lift as benchmark: ')
#print((df_pivot['buyer_rate_nov'] - df_pivot['buyer_rate_oct']) / (df_pivot['buyer_rate_nov'] - df_pivot['buyer_rate_oct'])[0])

11. vs. 10. each group's conversion lift contribution:
each group's actucal conversion lift:
 active_group
1_day_active               1.055%
2_days_active              1.201%
3_days_active              1.512%
more_than_3_days_active    5.271%
dtype: object

each group's conversion lift mom:
 active_group
1_day_active               33.059%
2_days_active               9.058%
3_days_active               6.379%
more_than_3_days_active    13.403%
dtype: object

overall buyer conversion lift contribution:
 active_group
1_day_active               63.669%
2_days_active              11.017%
3_days_active               4.681%
more_than_3_days_active    20.633%
dtype: object

Based on the above table, the buyer conversion rate tends to increase as total active day increases in a month. However, given a large amount of user base of `1_day_active` group, the group contributes the most to overall buyer conversion lift (Nov. vs. Oct.), accounting for 63.67%.

This therefore leads to 2 questions:

- Is a user having more active days on the platform more likely to make purchases in a month?  
- Why did the Nov.'s buyer conversion of `1_day_active` group rise compared to Oct.'s? What it possibly related with?

Is a user having more active days more likely to make purchases in a month? 

The previous total active day metric defines a user as active in a day if the user had at least one session with any types of action recorded. By this definition, irrelevant active days can be captured. For instance, a user could be active (view products, add products to cart) after making purchases in the month, those active days are irrelevant to interpret if a user could be transitioned to a buyer. 

To more precisely observe the relation between number of active day of user and the user's buyer status, the metric is designed as:

For Oct. and Nov.:
- Based on `2_days_active`, `3_days_active`, and `more_than_3_days_active` groups, select the users who didn't make their first purchase at their first active day in a month. Only consider their event logs before (and including) their first purchase in a month, for users without any purchases in that month, all of their event logs will also be considered.
- For the following 10 days, a user will be marked as early returned active user if they had at least 1 session with any actions. Users didn't make early returns are defined as their second active day occured after the following 10 day period. Users who didn't make any of purchases in a month are also categorized to this group. 
- Analyze, compare each group's buyer conversion (if they were finally transitioned to a buyer in the month).

In [33]:
df_1 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'buyer at first active day',
                'cosmetics_shop_data'
)

df_1_agg = df_1.groupby('month_start').agg({
    'total_base': 'sum',
    'is_buyer_first_day_total': 'sum'}).reset_index()
df_1_agg['buyer_rate'] = df_1_agg['is_buyer_first_day_total'] / df_1_agg['total_base']

For each month, over 90% of users from the groups: `2_days_active`, `3_days_active`, and `more_than_3_days_active` didn't make their purchases at their first month active day.

In [35]:
df_1_agg['non_buyer_rate'] = 1 - df_1_agg['buyer_rate']
df_1_agg['type'] = 'first_active_day_not_purchased'
df_plot = df_1_agg.iloc[:, [0, 3]].copy()
df_plot['type'] = 'first_active_day_purchased'

df_plot = pd.concat([df_plot.rename(columns={'buyer_rate': 'Portion'}), df_1_agg.iloc[:, [0,4,5]].rename(columns={'non_buyer_rate': 'Portion'})], axis=0, ignore_index=True)
fig = px.bar(df_plot, x='month_start', y='Portion', color='type', barmode='stack')
fig.update_layout(template = 'plotly_white', width = 800, title = 'First active day purchased vs. not purchased', xaxis_title = 'Month')

Users having more than 1 active day in a month with early returning records (within 10 days) had higher buyer conversion rate, compared to users who didn't have such records.

In [37]:
df_2 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'daily October November cohorts early return and subsequent purchase',
                'cosmetics_shop_data'
)

In [38]:
fig = px.line(df_2, x='first_active_date', y='subsequent_purchase_rate', color = 'early_return_group')
fig.update_layout(template = 'plotly_white', xaxis_title = 'First active date', yaxis_title= 'Subsequent purchase rate',
                  title = 'Subsequent buyer conversion (10 day window)')

Further segment the early returned user group based on their total active days during the 10 day window, and compare each group's subsequent buyer conversion.

In [97]:
df_3 = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'daily cohorts by early active days and subsequent purchase',
                'cosmetics_shop_data'
)

df_3['first_active_date'] = pd.to_datetime(df_3['first_active_date'])
df_3['month'] = df_3['first_active_date'].dt.month

In [101]:
df_3_agg = df_3.query('month == 10 or month == 11').groupby(['month', 'early_active_days_group']).agg({
    'total_users': 'sum',
    'subsequent_buyers': 'sum'
}).reset_index()
df_3_agg['buyer_rate'] = df_3_agg['subsequent_buyers'] / df_3_agg['total_users']
df_3_agg['early_active_days_group'] = pd.Categorical(df_3_agg['early_active_days_group'], 
                                                     categories= ['0', '[1, 3]', '[4, 6]', '[7, 10]'], 
                                                     ordered=True)
df_3_agg = df_3_agg.sort_values(['month', 'early_active_days_group'])
fig = px.bar(df_3_agg, x='month', y ='buyer_rate', color ='early_active_days_group', barmode='group')
fig.update_layout(template = 'plotly_white', xaxis_title = 'Month', yaxis_title ='Buyer rate', title = 'Total active days during 10 day window segmentation')

Higher early total active days showed a higher subsequent buyer conversion in a month. However, a significant group user base difference between `early_active_days_group 0` and the other groups should be noticed.

In [ ]:
display(pd.merge(df_3_agg.iloc[:4, 1:], df_3_agg.iloc[4:, 1:], on = 'early_active_days_group', how = 'inner', suffixes=('_oct', '_nov')))

,early_active_days_group,total_users_oct,subsequent_buyers_oct,buyer_rate_oct,total_users_nov,subsequent_buyers_nov,buyer_rate_nov
0,0,323890,1164.0,0.003594,281721,1459.0,0.005179
1,"[1, 3]",47384,1489.0,0.031424,52879,1952.0,0.036914
2,"[4, 6]",2318,286.0,0.123382,2781,365.0,0.131248
3,"[7, 10]",287,42.0,0.146341,342,66.0,0.192982

Why `1_day_active` group Nov. buyer conversion raised compared to Oct.? What it possibly relates with?

In [64]:
df_nov = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '11. 2019 one-day-active users sessions and buyer status',
                'cosmetics_shop_data'
)

df_oct = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                '10. 2019 one-day-active users by session group',
                'cosmetics_shop_data'
)

df_nov_agg = df_nov.groupby('session_group').agg({
    'user_id': 'count',
    'is_buyer': 'sum',
    'total_purchase_gmv': 'sum'
}).reset_index().rename(columns={'user_id': 'total_base', 'is_buyer': 'total_buyer'})
df_nov_agg['portion'] = df_nov_agg['total_base'] / (df_nov_agg['total_base']).sum()
df_nov_agg['buyer_rate'] = df_nov_agg['total_buyer'] / df_nov_agg['total_base']
df_nov_agg['gmv/buyer'] = df_nov_agg['total_purchase_gmv'] / df_nov_agg['total_buyer']

df_oct_agg = df_oct.groupby('session_group').agg({
    'user_id': 'count',
    'is_buyer': 'sum',
    'total_purchase_gmv': 'sum'
}).reset_index().rename(columns={'user_id': 'total_base', 'is_buyer': 'total_buyer'})
df_oct_agg['portion'] = df_oct_agg['total_base'] / (df_oct_agg['total_base']).sum()
df_oct_agg['buyer_rate'] = df_oct_agg['total_buyer'] / df_oct_agg['total_base']
df_oct_agg['gmv/buyer'] = df_oct_agg['total_purchase_gmv'] / df_oct_agg['total_buyer']

In [65]:
df_combined = pd.merge(df_nov_agg, df_oct_agg, on ='session_group', how = 'inner', suffixes=('_nov', '_oct'))
df_combined['session_group'] = pd.Categorical(
    df_combined['session_group'],
    categories= ['[1, 10]', '(10, 20]', '(20, 50]', '(50, 100]', '(100, inf]'],
    ordered=True
)
df_combined = df_combined.sort_values('session_group').reset_index().iloc[:, 1:]
df_combined

,session_group,total_base_nov,total_buyer_nov,total_purchase_gmv_nov,portion_nov,buyer_rate_nov,gmv/buyer_nov,total_base_oct,total_buyer_oct,total_purchase_gmv_oct,portion_oct,buyer_rate_oct,gmv/buyer_oct
0,"[1, 10]",286094,11579,404703.29,0.993786,0.040473,34.951489,327378,10008,346444.86,0.995463,0.030570,34.616793
1,"(10, 20]",1128,365,14863.09,0.003918,0.323582,40.720795,972,263,10441.70,0.002956,0.270576,39.702281
2,"(20, 50]",527,207,11679.36,0.001831,0.392789,56.422029,446,196,8226.36,0.001356,0.439462,41.971224
3,"(50, 100]",117,65,3212.72,0.000406,0.555556,49.426462,64,24,1323.44,0.000195,0.375000,55.143333
4,"(100, inf]",17,7,529.21,0.000059,0.411765,75.601429,10,3,590.41,0.000030,0.300000,196.803333

By segementing user base by total sessions in a day, Nov.'s structure shifting effect had relatively small contribution to the overall buyer conversion lift (`1_day_active user` group), only accounting for 4.79%. Mainly contributed to each group's conversion lift.

In [70]:
print('Oct. vs. Nov. buyer conversion: \n')
oct_conv =  df_combined['total_buyer_oct'].sum() / df_combined['total_base_oct'].sum()
print('Oct. conversion: ', show_decimal_to_percentage(oct_conv, 3))
nov_conv = df_combined['total_buyer_nov'].sum() / df_combined['total_base_nov'].sum()
print('Nov. conversion: ', show_decimal_to_percentage(nov_conv, 3))
print("11. vs. 10. actual conversion lift: ", show_decimal_to_percentage(nov_conv - oct_conv, 3))
print("11. user group structure shifting effect: ", show_decimal_to_percentage((df_combined['portion_nov'] * df_combined['buyer_rate_oct']).sum() - oct_conv, 3))
print("Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain: ", show_decimal_to_percentage(
    ((df_combined['portion_nov'] * df_combined['buyer_rate_oct']).sum() - oct_conv)/(nov_conv - oct_conv), 3
))
print("11. user group conversion lift effect can explain: ", show_decimal_to_percentage(
    1 - ((df_combined['portion_nov'] * df_combined['buyer_rate_oct']).sum() - oct_conv)/(nov_conv - oct_conv), 3
))

Oct. vs. Nov. buyer conversion:

Oct. conversion:  3.191%
Nov. conversion:  4.246%
11. vs. 10. actual conversion lift:  1.055%
11. user group structure shifting effect:  0.051%
Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain:  4.794%
11. user group conversion lift effect can explain:  95.206%

Total sessions of the [1, 10] group contributes to most of the overall conversion lift, accounting for 97.99%.

In [78]:
print('Each group\'s contribution to overall conversion lift: ')
print((
    df_combined['portion_nov'] * (df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct']) / (
    df_combined['portion_nov'] * (df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct'])
).sum()
).map(lambda x: show_decimal_to_percentage(x, 3)))

Each group's contribution to overall conversion lift:
0    97.986%
1     2.068%
2    -0.851%
3     0.731%
4     0.066%
dtype: object

Further brakdown the core group: users have total sessions in [1, 10] in a month.

In [105]:
df_nov = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'November 2019 one-day-active users by sessions 1 to 10',
                'cosmetics_shop_data'
)

df_oct = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'October 2019 one-day-active users by sessions 1 to 10',
                'cosmetics_shop_data'
)

df_nov['portion'] = df_nov['total_base'] / df_nov['total_base'].sum()
df_oct['portion'] = df_oct['total_base'] / df_oct['total_base'].sum()

In [106]:
df_combined = pd.merge(df_nov, df_oct, on ='total_sessions', how = 'inner', suffixes=('_nov', '_oct'))
df_combined

,total_sessions,total_base_nov,total_buyer_nov,buyer_rate_nov,portion_nov,total_base_oct,total_buyer_oct,buyer_rate_oct,portion_oct
0,1,241629,7044.0,0.0292,0.844579,285246,6314.0,0.0221,0.871305
1,2,30973,2406.0,0.0777,0.108262,29508,2013.0,0.0682,0.090134
2,3,6949,918.0,0.1321,0.024289,6487,731.0,0.1127,0.019815
3,4,2672,412.0,0.1542,0.009340,2469,317.0,0.1284,0.007542
4,5,1379,218.0,0.1581,0.004820,1353,202.0,0.1493,0.004133
5,6,903,189.0,0.2093,0.003156,845,137.0,0.1621,0.002581
6,7,588,128.0,0.2177,0.002055,530,82.0,0.1547,0.001619
7,8,412,109.0,0.2646,0.001440,401,82.0,0.2045,0.001225
8,9,322,81.0,0.2516,0.001126,307,73.0,0.2378,0.000938
9,10,267,74.0,0.2772,0.000933,232,57.0,0.2457,0.000709

In [107]:
print('Oct. vs. Nov. buyer conversion: \n')
oct_conv =  df_combined['total_buyer_oct'].sum() / df_combined['total_base_oct'].sum()
print('Oct. conversion: ', show_decimal_to_percentage(oct_conv, 3))
nov_conv = df_combined['total_buyer_nov'].sum() / df_combined['total_base_nov'].sum()
print('Nov. conversion: ', show_decimal_to_percentage(nov_conv, 3))
print("11. vs. 10. actual conversion lift: ", show_decimal_to_percentage(nov_conv - oct_conv, 3))
print("11. user group structure shifting effect: ", show_decimal_to_percentage((df_combined['portion_nov'] * df_combined['buyer_rate_oct']).sum() - oct_conv, 3))
print("Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain: ", show_decimal_to_percentage(
    ((df_combined['portion_nov'] * df_combined['buyer_rate_oct']).sum() - oct_conv)/(nov_conv - oct_conv), 3
))
print("11. user group conversion lift effect can explain: ", show_decimal_to_percentage(
    1 - ((df_combined['portion_nov'] * df_combined['buyer_rate_oct']).sum() - oct_conv)/(nov_conv - oct_conv), 3
))

Oct. vs. Nov. buyer conversion:

Oct. conversion:  3.057%
Nov. conversion:  4.047%
11. vs. 10. actual conversion lift:  0.99%
11. user group structure shifting effect:  0.176%
Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain:  17.73%
11. user group conversion lift effect can explain:  82.27%

In [109]:
print('Each group\'s actucal conversion lift: ')
print((
    df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct']
).map(lambda x: show_decimal_to_percentage(x, 3)))

print()

print('Each group\'s contribution to overall conversion lift: ')
print((
    df_combined['portion_nov'] * (df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct']) / (
    df_combined['portion_nov'] * (df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct'])
).sum()
).map(lambda x: show_decimal_to_percentage(x, 3)))

Each group's actucal conversion lift:
0    0.71%
1    0.95%
2    1.94%
3    2.58%
4    0.88%
5    4.72%
6     6.3%
7    6.01%
8    1.38%
9    3.15%
dtype: object

Each group's contribution to overall conversion lift:
0    73.222%
1    12.559%
2     5.754%
3     2.942%
4     0.518%
5     1.819%
6     1.581%
7     1.057%
8      0.19%
9     0.359%
dtype: object

Users that have total sessions of 1, 2, and 3 in a day account for 90% of the overall buyer conversion ( [1, 10] group from `1_day_active` base) lift. What product-side factors potentially led more purchased users in Nov.?

Since 40% of the product's brand attribute in the dataset are NA and the product's category attribute only contains encoded id that is useless for analysis, the most efficient prodcut's attribute comes to its price.

Two ways of segmentation that related to the business are adopted:

- Is the price tier structure of the product these users had first exposure to (defined as first viewd product) in this month changed?

- Is the price tier structure of the product these users mostly interacted (only consider view and add cart) with in this month changed?

Is the price tier structure of the product these users had first exposure to (defined as first viewd product) in this month changed?

In [110]:
df_nov = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'November 2019 selected users first view and buyer status',
                'cosmetics_shop_data'
)

df_oct = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'October 2019 selected users first view and buyer status',
                'cosmetics_shop_data'
)

In [113]:
print('Nov. users whose event logs didn\'t contain view during the specified period: ', 
      show_decimal_to_percentage(df_nov['first_view_time'].isna().sum() / len(df_nov), 3))

print('Oct. users whose event logs didn\'t contain view during the specified period: ', 
      show_decimal_to_percentage(df_oct['first_view_time'].isna().sum() / len(df_oct), 3))

Nov. users whose event logs didn't contain view during the specified period:  4.263%
Oct. users whose event logs didn't contain view during the specified period:  3.36%

In [79]:
df_nov_non_na = df_nov[df_nov['first_view_time'].notna()].copy()
df_nov_non_na['price_group'] = pd.cut(
    df_nov_non_na['price'],
    bins=[0, 3, 5, 10, 20, 50, np.inf],
    labels=['<3', '3–<5', '5–<10', '10–<20', '20–<50', '≥50'],
    right=False
)
df_nov_agg = (
    df_nov_non_na.groupby('price_group', observed=False)
    .agg(
        total_users=('user_id', 'size'),
        total_buyers=('is_buyer', 'sum'),
        buyer_rate=('is_buyer', 'mean')
    )
    .reset_index()
)
df_nov_agg['portion'] = df_nov_agg['total_users'] / df_nov_agg['total_users'].sum()


df_oct_non_na = df_oct[df_oct['first_view_time'].notna()].copy()
df_oct_non_na['price_group'] = pd.cut(
    df_oct_non_na['price'],
    bins=[0, 3, 5, 10, 20, 50, np.inf],
    labels=['<3', '3–<5', '5–<10', '10–<20', '20–<50', '≥50'],
    right=False
)
df_oct_agg = (
    df_oct_non_na.groupby('price_group', observed=False)
    .agg(
        total_users=('user_id', 'size'),
        total_buyers=('is_buyer', 'sum'),
        buyer_rate=('is_buyer', 'mean')
    )
    .reset_index()
)
df_oct_agg['portion'] = df_oct_agg['total_users'] / df_oct_agg['total_users'].sum()

In [80]:
print('Oct. vs. Nov. buyer conversion: \n')
oct_conv =  (df_oct_agg['portion'] * df_oct_agg['buyer_rate']).sum()
print('Oct. conversion: ', show_decimal_to_percentage(oct_conv, 3))
nov_conv = (df_nov_agg['portion'] * df_nov_agg['buyer_rate']).sum()
print('Nov. conversion: ', show_decimal_to_percentage(nov_conv, 3))
print("11. vs. 10. actual conversion lift: ", show_decimal_to_percentage(nov_conv - oct_conv, 3))
print("11. user group structure shifting effect: ", show_decimal_to_percentage((df_nov_agg['portion'] * df_oct_agg['buyer_rate']).sum() - oct_conv, 3))
print("Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain: ", show_decimal_to_percentage(
    ((df_nov_agg['portion'] * df_oct_agg['buyer_rate']).sum() - oct_conv) / (nov_conv - oct_conv), 3
))
print("11. user group conversion lift effect can explain: ", show_decimal_to_percentage(
    1 - ((df_nov_agg['portion'] * df_oct_agg['buyer_rate']).sum() - oct_conv) / (nov_conv - oct_conv), 3
))

Oct. vs. Nov. buyer conversion:

Oct. conversion:  2.42%
Nov. conversion:  3.238%
11. vs. 10. actual conversion lift:  0.819%
11. user group structure shifting effect:  -0.016%
Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain:  -1.951%
11. user group conversion lift effect can explain:  101.951%

In [82]:
df_combined = pd.merge(df_nov_agg, df_oct_agg, on ='price_group', how = 'inner', suffixes=('_nov', '_oct'))
df_combined

,price_group,total_users_nov,total_buyers_nov,buyer_rate_nov,portion_nov,total_users_oct,total_buyers_oct,buyer_rate_oct,portion_oct
0,<3,54448,1862,0.034198,0.203441,65420,1514,0.023143,0.210728
1,3–<5,49732,1668,0.033540,0.185820,57784,1376,0.023813,0.186132
2,5–<10,65247,2330,0.035710,0.243791,79762,2056,0.025777,0.256926
3,10–<20,46094,1628,0.035319,0.172227,53532,1565,0.029235,0.172435
4,20–<50,28555,866,0.030327,0.106694,30228,713,0.023587,0.097369
5,≥50,23559,313,0.013286,0.088027,23721,288,0.012141,0.076409

Is the price tier structure of the product these users mostly interacted (only consider view and add cart) with in this month changed?

In [59]:
df_nov = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'November 2019 selected users most interacted product',
                'cosmetics_shop_data'
)

df_oct = query_from_file(f'{parent_dir}/sql_scripts/explore_v2.sql',
                'October 2019 selected users most interacted product',
                'cosmetics_shop_data'
)

In [64]:
df_nov['price_group'] = pd.cut(
    df_nov['price'],
    bins=[0, 3, 5, 10, 20, 50, np.inf],
    labels=['<3', '3–<5', '5–<10', '10–<20', '20–<50', '≥50'],
    right=False
)
df_nov_agg = (
    df_nov.groupby('price_group', observed=False)
    .agg(
        total_users=('user_id', 'size'),
        total_buyers=('is_buyer', 'sum'),
        buyer_rate=('is_buyer', 'mean')
    )
    .reset_index()
)
df_nov_agg['portion'] = df_nov_agg['total_users'] / df_nov_agg['total_users'].sum()

df_oct['price_group'] = pd.cut(
    df_oct['price'],
    bins=[0, 3, 5, 10, 20, 50, np.inf],
    labels=['<3', '3–<5', '5–<10', '10–<20', '20–<50', '≥50'],
    right=False
)
df_oct_agg = (
    df_oct.groupby('price_group', observed=False)
    .agg(
        total_users=('user_id', 'size'),
        total_buyers=('is_buyer', 'sum'),
        buyer_rate=('is_buyer', 'mean')
    )
    .reset_index()
)
df_oct_agg['portion'] = df_oct_agg['total_users'] / df_oct_agg['total_users'].sum()

In [65]:
print('Oct. vs. Nov. buyer conversion: \n')
oct_conv =  (df_oct_agg['portion'] * df_oct_agg['buyer_rate']).sum()
print('Oct. conversion: ', show_decimal_to_percentage(oct_conv, 3))
nov_conv = (df_nov_agg['portion'] * df_nov_agg['buyer_rate']).sum()
print('Nov. conversion: ', show_decimal_to_percentage(nov_conv, 3))
print("11. vs. 10. actual conversion lift: ", show_decimal_to_percentage(nov_conv - oct_conv, 3))
print("11. user group structure shifting effect: ", show_decimal_to_percentage((df_nov_agg['portion'] * df_oct_agg['buyer_rate']).sum() - oct_conv, 3))
print("Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain: ", show_decimal_to_percentage(
    ((df_nov_agg['portion'] * df_oct_agg['buyer_rate']).sum() - oct_conv) / (nov_conv - oct_conv), 3
))
print("11. user group conversion lift effect can explain: ", show_decimal_to_percentage(
    1 - ((df_nov_agg['portion'] * df_oct_agg['buyer_rate']).sum() - oct_conv) / (nov_conv - oct_conv), 3
))

Oct. vs. Nov. buyer conversion:

Oct. conversion:  2.765%
Nov. conversion:  3.636%
11. vs. 10. actual conversion lift:  0.871%
11. user group structure shifting effect:  -0.024%
Portion of overall buyer conversion lift that 11. user group structure shifting effect can explain:  -2.766%
11. user group conversion lift effect can explain:  102.766%

In [69]:
df_combined = pd.merge(df_nov_agg, df_oct_agg, on ='price_group', how = 'inner', suffixes=('_nov', '_oct'))
df_combined

,price_group,total_users_nov,total_buyers_nov,buyer_rate_nov,portion_nov,total_users_oct,total_buyers_oct,buyer_rate_oct,portion_oct
0,<3,59567,2883,0.048399,0.213769,70091,2427,0.034626,0.218716
1,3–<5,52056,1856,0.035654,0.186814,59831,1572,0.026274,0.186700
2,5–<10,67762,2595,0.038296,0.243179,81787,2154,0.026337,0.255213
3,10–<20,47246,1780,0.037675,0.169553,54696,1771,0.032379,0.170676
4,20–<50,28546,763,0.026729,0.102444,30418,689,0.022651,0.094918
5,≥50,23474,256,0.010906,0.084242,23643,249,0.010532,0.073777

In [75]:
print('Each group\'s actucal conversion lift: ')
print((
    df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct']
).map(lambda x: show_decimal_to_percentage(x, 3)))
print()
print('Each group\'s contribution to overall conversion lift: ')
print((
    df_combined['portion_nov'] * (df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct']) / (df_combined['portion_nov'] * (df_combined['buyer_rate_nov'] - df_combined['buyer_rate_oct'])).sum()
).map(lambda x: show_decimal_to_percentage(x, 3)))

Each group's actucal conversion lift:
0    1.377%
1    0.938%
2    1.196%
3     0.53%
4    0.408%
5    0.037%
dtype: object

Each group's contribution to overall conversion lift:
0    32.889%
1    19.575%
2    32.487%
3    10.031%
4     4.666%
5     0.352%
dtype: object