In [2]:
import pandas as pd
import numpy as np
import os

In [11]:
parent_dir = os.path.dirname(os.getcwd())
years = [2019, 2020]
df = pd.DataFrame()

for year in years:
    if year == 2019:
        months = ['Oct', 'Nov', 'Dec']
        for month in months:
            df_temp = pd.read_csv(os.path.join(parent_dir, f'./{year}-{month}.csv'))
            df = pd.concat([df, df_temp], axis = 0)
    else:
        months = ['Jan', 'Feb']
        for month in months:
            df_temp = pd.read_csv(os.path.join(parent_dir, f'./{year}-{month}.csv'))
            df = pd.concat([df, df_temp], axis=0)

In [12]:
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,cart,5773203,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
1,2019-10-01 00:00:03 UTC,cart,5773353,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
2,2019-10-01 00:00:07 UTC,cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
3,2019-10-01 00:00:07 UTC,cart,5723490,1487580005134238553,NaN,runail,2.62,463240011,26dd6e6e-4dac-4778-8d2c-92e149dab885
4,2019-10-01 00:00:15 UTC,cart,5881449,1487580013522845895,NaN,lovely,0.56,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9

# Data type

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20692840 entries, 0 to 4156681
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
dtypes: float64(1), int64(3), object(5)
memory usage: 1.5+ GB

# NA rate

In [29]:
for col in df.columns:
    print(f'{col} na rate: ', np.sum(df[col].isna()) * 100 / df.shape[0])

event_time na rate:  0.0
event_type na rate:  0.0
product_id na rate:  0.0
category_id na rate:  0.0
category_code na rate:  98.29122537070793
brand na rate:  42.3195511104324
price na rate:  0.0
user_id na rate:  0.0
user_session na rate:  0.02222024623009698

# Column unique values

categorical: `event_type`, `category_code`, `brand`

In [30]:
for col in df.columns:
    print(f'{col} unqiue values: ', len(df[col].value_counts()))

event_time unqiue values:  8782890
event_type unqiue values:  4
product_id unqiue values:  54571
category_id unqiue values:  525
category_code unqiue values:  12
brand unqiue values:  273
price unqiue values:  2860
user_id unqiue values:  1639358
user_session unqiue values:  4535941

In [35]:
for col in ['event_type', 'category_id', 'category_code', 'brand']:
    print(col + ':', list(df[col].value_counts().index))

event_type: ['view', 'cart', 'remove_from_cart', 'purchase']
category_id: [1487580007675986893, 1487580005595612013, 1487580005092295511, 1487580005671109489, 1487580006317032337, 1602943681873052386, 1487580005268456287, 1487580013841613016, 1487580005134238553, 1487580008246412266, 1487580009286598681, 1487580005754995573, 1487580006300255120, 1487580013950664926, 1487580009445982239, 1487580008145748965, 1487580005713052531, 1487580005511725929, 1487580005427839846, 1487580004916134735, 2084144451428549153, 1487580011585077370, 1487580010100293687, 1487580005050352469, 1487580013522845895, 1487580008263189483, 1487580005553668971, 1487580006350586771, 1487580005461394279, 2115334439910245200, 1487580009051717646, 1487580007432717250, 1487580009471148064, 1638456119066100510, 1487580009311764506, 1783999063314661546, 1487580007634043851, 1487580007910867929, 1487580012096782476, 1487580013581566154, 1487580007256556476, 1487580005411062629, 1487580007852147670, 1487580009387261981, 2151191071051219817, 1658462125284131265, 1783999064136745198, 1487580013069861041, 1487580008187692007, 1783999067156644376, 1783999072332415142, 1487580007717929935, 1487580009605365797, 1487580009143992338, 1487580010645553231, 2151191071378375538, 1487580004857414477, 1487580007281722301, 1487580009496313889, 1783999068909863670, 1487580011652186237, 1487580007936033754, 1487580010796548183, 1487580008800059394, 1487580011627020412, 1487580013749338323, 1487580008657454075, 1487580011283087468, 1487580011702517887, 1487580004832248652, 1487580013011140782, 1891434214553813877, 1487580007306888126, 1487580010628776014, 1487580010125459512, 1487580005008409427, 1487580013858390233, 1487580008313521133, 1487580012902088873, 1783999064103190764, 1487580012927254698, 1487580010561667147, 1897124478404526487, 1487580007575323592, 1511892746070131099, 1487580008288355308, 1487580006551913373, 1487580013053083824, 1487580007952810971, 1487580004882580302, 2195085255034011676, 1487580013279576251, 1487580013388628160, 1487580010872045658, 2007399943458784057, 1487580011383750769, 1487580008347075566, 1542195323827388674, 1487580013539623112, 1487580006895846315, 1783999071199952917, 1487580013506068678, 2089259162625114209, 1487580012994363565, 1487580006509970331, 2140803113261466607, 1487580013640286413, 1487580010821714008, 1924049110428549877, 1487580006132482952, 1487580007483048900, 1525995662934540829, 1605161575889502297, 1487580013413793985, 1487580008447738866, 1487580006962955182, 1487580012969197740, 1487580011677352062, 1487580009362096156, 1487580013489291461, 1487580005067129686, 1783999068867920626, 1487580007659209676, 1487580008112194531, 1597770225539875791, 1487580012021285001, 1487580011853512836, 2196456817641391019, 1487580005855658874, 1487580009177546772, 1487580005528503146, 1924049106385240809, 2193074740552270669, 2055161088059638328, 1487580009227878422, 1487580009202712597, 2193074740619379535, 2151191071118328683, 1487580013027917999, 1487580013229244601, 2141560642253881670, 1487580007399162817, 1487580011534745720, 1487580006434472855, 1487580009521479714, 1487580011308253293, 1487580013145358517, 1487580007776650194, 1487580008984608779, 2151191070984110951, 1495705810662064688, 1487580013170524342, 1487580014009385185, 1487580012574933146, 1487580010695884882, 1487580009261432856, 2069804417665728971, 1487580007592100809, 1487580012373606546, 1487580006409307030, 1487580013732561106, 1487580011501191286, 1487580012642042013, 1487580007457883075, 1842735758805303837, 1487580008774893569, 1842735760499802745, 1487580009026551821, 1921723491720102387, 1487580008758116352, 1487580010318397504, 1487580013472514244, 1487580006644188066, 1487580008162526182, 2151191070908613477, 1487580011408916594, 1487580008607122425, 1977575787259232875, 1783999076551885399, 2134354342373753638, 1761186209054327497, 1487580006937789357, 1487580007550157767, 1891434351850160381, 1487580007835370453, 2177933350667289121, 1937169073007756269, 1487580011425693811, 1982860263572898112, 1487580013254410426, 1487580013212467384, 1487580013824835799, 2029082628195353599, 1487580005385896804, 1783999064069636330, 1487580009076883471, 1487580010754605141, 1487580010779770966, 2114584564549550293, 1487580012683985055, 1783999073758478650, 1526733091857498510, 1783999071325782053, 2035665444290953519, 2195085258272014535, 2018395024110125980, 1487580013086638258, 1487580013690618064, 1487580009336930331, 1487580012524601496, 1487580008011531230, 1516331853567492962, 1982860244379763042, 1487580011996119176, 1487580006241534861, 1487580005897601916, 1487580009571811364, 1998040849203594085, 1495705810729173554, 1487580012591710363, 1487580007365608384, 1487580008053474272, 1487580013430571202, 1487580009622143014, 1487580013296353468, 1487580007894090712, 1487580011157258342, 1958278551207674674, 1487580013615120588, 1752742615205281895, 1487580006526747548, 1487580013128581300, 1487580012121948301, 1720400165430363096, 1487580008816836611, 1487580009118826513, 1645114480121610699, 1487580012717539489, 1487580010242900029, 1487580006451250072, 1487580008028308447, 1487580007189447609, 1814592470537732872, 1487580012432326804, 2193074740686488401, 2029731308699124089, 1487580010268065854, 1487580010721050707, 1871018959927509750, 1998040852064109417, 1487580011098538083, 1487580013657063630, 1487580011970953351, 1487580007986365405, 1487580010335174721, 1487580013799669974, 1897124495995438074, 2195085255176618020, 1487580010217734204, 1495705810704007729, 1487580007877313495, 1487580007524991942, 1858245586344477369, 1487580010377117763, 1487580013321519293, 1487580006073762693, 1911999801088541491, 1597769965795017114, 1487580007759872977, 1715102773747384334, 1487580010293231679, 1487580012205834384, 1819693959081886239, 1487580009672474664, 1487580013338296510, 2093602042093240877, 1487580010737827924, 1801635223591453292, 1487580009546645539, 1897124469017673788, 1487580013900333275, 1487580011517968503, 1933364344720982871, 1487580006199591819, 1487580010922377308, 1783999073792033086, 1487580008909111303, 2151191059751764547, 1715102762414375164, 1588205336064425989, 2164688961165852944, 1648815651034235876, 1911999801642189621, 1558526315760452545, 1487580008070251489, 1487580013917110492, 1933472286753424063, 1783999072365969578, 1752742606699234159, 1783999064036081896, 2095736144888071137, 1791442895991997390, 1487580011903844485, 1487580007214613434, 1487580007172670392, 1487580012457492629, 1487580012952420523, 1487580011182424167, 1487580005486560104, 2013754353822728372, 1487580005343953762, 1487580005838881657, 2195085255117897760, 1604427094756950459, 1487580012172279951, 1487580008087028706, 2193074740493550411, 1487580007072007091, 2151191075757228942, 1487580011476025461, 2106514244437541443, 2235524499636224267, 2196456817758831535, 2130081478220972046, 1554383493545328915, 1897124489259385629, 2187790129827939246, 1487580008699397117, 1487580010662330448, 1487580005629166447, 1487580011333419118, 1783999064170299632, 1532652067498229876, 1783999063574708423, 1783999072407912622, 1487580007046841266, 1921723506584715388, 1487580012876923048, 2018287324474901238, 1559261858748170632, 1660394382047576308, 1487580005293622112, 1487580010846879833, 1543705961326182546, 2106514244487873093, 1487580010192568379, 1487580005025186644, 1487580011241144426, 2235524499216793855, 1842735764509557576, 1487580011786403970, 1487580007021675441, 1797122099068797194, 1487580008422573041, 2022516588854378951, 1487580012616876188, 1487580011752849537, 1944358258223350494, 1889472915104072007, 1487580012809814181, 1783999076535108182, 1759024699007828783, 1804383582576181309, 1487580012784648356, 1487580013992607968, 1842735768846467167, 1487580006870680490, 2145935122136826354, 1487580007701152718, 1584505206060614455, 1487580006627410849, 1487580005880824699, 1487580011945787526, 2121383893343929118, 1791442849384891169, 2069171133327868014, 1487580006015042434, 2187686850687140020, 1805953852441101266, 1725504706412807026, 1487580007097172916, 1487580010955931741, 1487580006979732399, 1487580006056985476, 1998040850688377703, 1977786601392047073, 2055368408169447599, 1487580006098928518, 2071303198680810125, 1487580011601854587, 2222113024708182273, 2235524494015856752, 1547480590851244887, 2068966806634103136, 2094448780651791052, 1487580006568690590, 1487580007139115958, 1487580012734316706, 1487580006484804506, 1487580007113950133, 2154396123597373922, 1926797403503985079, 1487580014093271270, 1977683390215749955, 1487580006820348840, 1487580006711296933, 1487580011031429216, 1487580007004898224, 2020400296164851991, 1962525126503170858, 2028340285225828822, 1487580009823469613, 2151191059827262021, 1487580008858779653, 1487580012147114126, 2195085258179739843, 1924049287554007223, 1487580006845514665, 1487580014042939619, 2155132423103316327, 1487580013933887709, 1487580009739583530, 1911999948073730325, 1487580012071616651, 1810470908326838736, 1487580004983243602, 1487580009974464562, 1487580005922767741, 1487580006157648777, 1783999067181810204, 1487580004941300560, 1752742610406999036, 1487580006174425994, 1487580009647308839, 1487580012759482531, 1487580005318787937, 1657722039387029886, 1911999884991397970, 2027602240612598357, 1962525118928257818, 1987724780047958178, 1962525462299148572, 2022622168218599898, 1487580012507824279, 1487580010360340546, 1977575775473238831, 2195085258339123402, 1936327050549789532, 1487580005998265217, 2060156961931919712, 2134354356349173879, 1759024698982662957, 1487580008590345208, 2069804424703771380, 1487580013564788937, 1487580008128971748, 1913479463425802701, 2242903426784559183, 1628099626433249931, 1487580008674231292, 1487580005176181595, 1487580010150625337, 1487580009798303788, 1487580008951054345, 1487580010075127862, 1487580011828347011, 1487580008472904691, 1487580012046450826, 1487580004807082827, 1604427145138930210, 1487580008221246441, 1487580006610633632, 1805953965678920077, 1487580012482658454, 1487580006585467807, 1842735764450837316, 2166295400451933025, 1791442703716712702, 1487580005570446188, 1487580007508214725, 1487580008925888520, 1487580004966466385, 1752742617696698537, 1487580008523236341, 1487580005687886706, 1487580010989486174, 1487580009764749355, 1487580005939544958, 1487580011006263391, 1648815843896722076, 1487580013782892757, 1487580012851757223, 1487580011559911545, 1487580009009774604, 1487580005796938615, 1487580011115315300, 1487580011199201384, 1487580008565179383, 1487580005369119587, 1487580011450859636, 2053031020655018687, 1487580010603610189, 1495705810754339379, 1487580010427449413, 1487580010049962037, 1487580006744851367, 1487580011073372258, 1487580005654332272, 1487580011224367209, 1487580006216369036, 1487580012658819230, 1487580012231000209, 1487580013363462335, 1487580009857024046, 1487580012549767321, 1487580011140481125, 1487580008204469224, 1487580010024796212, 1487580005159404378, 1487580007155893175, 1487580013715783889, 1487580011056595041, 1487580010897211483, 1487580009706029097, 1487580009890578479]
category_code: ['appliances.environment.vacuum', 'stationery.cartrige', 'apparel.glove', 'furniture.living_room.cabinet', 'accessories.bag', 'furniture.bathroom.bath', 'appliances.personal.hair_cutter', 'accessories.cosmetic_bag', 'appliances.personal.massager', 'appliances.environment.air_conditioner', 'furniture.living_room.chair', 'sport.diving']
brand: ['runail', 'irisk', 'masura', 'grattol', 'bpw.style', 'ingarden', 'estel', 'kapous', 'jessnail', 'uno', 'freedecor', 'italwax', 'concept', 'bluesky', 'pole', 'haruyama', 'cnd', 'milv', 'domix', 'lianail', 'cosmoprofi', 'zinger', 'oniq', 'staleks', 'f.o.x', 'nagaraku', 'lovely', 'uskusi', 'beautix', 'yoko', 'pnb', 'airnails', 'de.lux', 'severina', 'metzger', 'roubloff', 'art-visage', 'browxenna', 'strong', 'kinetics', 'solomeya', 'shik', 'ardell', 'kaaral', 'rosi', 'levrana', 'swarovski', 'smart', 'farmstay', 'markell', 'polarus', 'max', 'marathon', 'lador', 'dewal', 'beauty-free', 'depilflax', 'bioaqua', 'sunuv', 'jas', 'matrix', 'artex', 'nitrimax', 'dizao', 'emil', 'sophin', 'kosmekka', 'missha', 'benovy', 'levissime', 'refectocil', 'happyfons', 'entity', 'shary', 'farmavita', 'skinlite', 'thuya', 'ecolab', 'trind', 'konad', 'kaypro', 'igrobeauty', 'bodyton', 'insight', 'limoni', 'dartnails', 'provoc', 'soleo', 'opi', 'relouis', 'kiss', 'siberina', 'zeitun', 'orly', 'dermacol', 'estelare', 'dermal', 'i-laq', 'eunyul', 'matreshka', 'jaguar', 'keen', 'mavala', 'farmona', 'tertio', 'kocostar', 'elskin', 'moyou', 'profhenna', 'lamixx', 'balbcare', 'bielenda', 'coifin', 'gehwol', 'lakme', 'parachute', 'lsanic', 'babyliss', 'lowence', 'keune', 'naomi', 'joico', 'enigma', 'freshbubble', 'estrade', 'cristalinas', 'osmo', 'petitfee', 'likato', 'chi', 'almea', 'vilenta', 'coocla', 'kims', 'nitrile', 'godefroy', 'kezy', 'batiste', 'vosev', 'deoproce', 'laboratorium', 'gezatone', 'candy', 'lebelage', 'kerasys', 'cutrin', 'ellips', 'yllozure', 'luxvisage', 'avene', 'inm', 'bespecial', 'glysolid', 'protokeratin', 'treaclemoon', 'enas', 's.care', 'riche', 'blixz', 'beauugreen', 'elizavecca', 'grace', 'biofollica', 'supertan', 'nefertiti', 'barex', 'meisterwerk', 'consly', 'note', 'beautific', 'tannymaxx', 'carmex', 'ecocraft', 'inoface', 'ypsed', 'bergamo', 'coxir', 'yu-r', 'dr.gloderm', 'koelf', 'ladykin', 'sanoto', 'latinoil', 'rasyan', 'nirvel', 'naturmed', 'kamill', 'litaline', 'miskin', 'plazan', 'fancy', 'ermine', 'sawa', 'enjoy', 'cruset', 'biorepair', 'veraclara', 'beautyblender', 'aura', 'egomania', 'vichy', 'profepil', 'greymy', 'mayamy', 'biore', 'herbolive', 'fedua', 'eos', 'finish', 'dorena', 'sun', 'marutaka-foot', 'mielle', 'termix', 'koreatida', 'mane', 'cosima', 'binacil', 'bioderma', 'koelcia', 'skipofit', 'tazol', 'andrea', 'kondor', 'kares', 'cettua', 'labay', 'foamie', 'arganoil', 'tosowoong', 'neoleor', 'radius', 'resize', 'frozen', 'helloganic', 'fly', 'juno', 'weaver', 'dobrovit', 'ovale', 'busch', 'australis', 'philips', 'everyang', 'rocknailstar', 'zab', 'bosnic', 'skinity', 'laiseven', 'dancoly', 'esquire', 'rorec', 'lunaris', 'barbie', 'pilaten', 'blise', 'embryolisse', 'essie', 'uralsoap', 'cuccio', 'bodipure', 'macadamia', 'ibd', 'ikoo', 'invisibobble', 'nova', 'footlogix', 'voesh', 'shifei', 'vl-gel', 'dessata', 'gena', 'pueen']

# Duplicated rows

In [37]:
df.duplicated().any()

np.True_

In [41]:
print('duplicated rows: ', len(df) - len(df.drop_duplicates()))

duplicated rows:  1109098

In [42]:
df_2 = df[df.duplicated(keep=False)]
df_2.head(40)

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
12,2019-10-01 00:00:30 UTC,remove_from_cart,5809103,1487580013522845895,NaN,irisk,0.60,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
13,2019-10-01 00:00:30 UTC,remove_from_cart,5809103,1487580013522845895,NaN,irisk,0.60,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
29,2019-10-01 00:01:05 UTC,remove_from_cart,5858981,1487580007634043851,NaN,de.lux,0.79,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
30,2019-10-01 00:01:05 UTC,remove_from_cart,5858981,1487580007634043851,NaN,de.lux,0.79,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
34,2019-10-01 00:01:07 UTC,remove_from_cart,5312,1487580009471148064,NaN,runail,1.27,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486
36,2019-10-01 00:01:07 UTC,remove_from_cart,5312,1487580009471148064,NaN,runail,1.27,467916806,2f5b5546-b8cb-9ee7-7ecd-84276f8ef486
37,2019-10-01 00:01:10 UTC,remove_from_cart,5823915,1487580007432717250,NaN,milv,1.59,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
38,2019-10-01 00:01:10 UTC,remove_from_cart,5823915,1487580007432717250,NaN,milv,1.59,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
50,2019-10-01 00:01:24 UTC,remove_from_cart,5664641,1487580011425693811,NaN,NaN,0.70,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
51,2019-10-01 00:01:24 UTC,remove_from_cart,5664641,1487580011425693811,NaN,NaN,0.70,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
62,2019-10-01 00:01:38 UTC,remove_from_cart,5620908,1487580005855658874,NaN,runail,2.22,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
63,2019-10-01 00:01:38 UTC,remove_from_cart,5620908,1487580005855658874,NaN,runail,2.22,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
66,2019-10-01 00:01:45 UTC,remove_from_cart,60183,1487580009445982239,NaN,runail,1.98,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
67,2019-10-01 00:01:45 UTC,remove_from_cart,60183,1487580009445982239,NaN,runail,1.98,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
76,2019-10-01 00:02:13 UTC,remove_from_cart,5820713,1487580006317032337,NaN,NaN,2.22,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694
77,2019-10-01 00:02:13 UTC,remove_from_cart,5820713,1487580006317032337,NaN,NaN,2.22,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694
105,2019-10-01 00:03:12 UTC,remove_from_cart,5881439,1487580013522845895,NaN,lovely,6.83,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
107,2019-10-01 00:03:12 UTC,remove_from_cart,5881439,1487580013522845895,NaN,lovely,6.83,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
108,2019-10-01 00:03:13 UTC,remove_from_cart,5836527,1487580013522845895,NaN,nagaraku,0.63,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
109,2019-10-01 00:03:13 UTC,remove_from_cart,5836527,1487580013522845895,NaN,nagaraku,0.63,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
130,2019-10-01 00:04:14 UTC,remove_from_cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
131,2019-10-01 00:04:14 UTC,remove_from_cart,5881589,2151191071051219817,NaN,lovely,13.48,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
133,2019-10-01 00:04:15 UTC,remove_from_cart,5802443,2151191070908613477,NaN,NaN,4.92,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
134,2019-10-01 00:04:15 UTC,remove_from_cart,5802443,2151191070908613477,NaN,NaN,4.92,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
137,2019-10-01 00:04:16 UTC,remove_from_cart,5861342,1487580010645553231,NaN,NaN,1.90,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
138,2019-10-01 00:04:16 UTC,remove_from_cart,5861342,1487580010645553231,NaN,NaN,1.90,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
139,2019-10-01 00:04:17 UTC,remove_from_cart,5854580,1487580010645553231,NaN,jessnail,3.81,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
140,2019-10-01 00:04:17 UTC,remove_from_cart,5854580,1487580010645553231,NaN,jessnail,3.81,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
141,2019-10-01 00:04:18 UTC,remove_from_cart,5800788,1487580007256556476,NaN,NaN,4.52,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
142,2019-10-01 00:04:18 UTC,remove_from_cart,5800788,1487580007256556476,NaN,NaN,4.52,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
144,2019-10-01 00:04:19 UTC,remove_from_cart,5836522,1487580013522845895,NaN,nagaraku,0.40,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
145,2019-10-01 00:04:19 UTC,remove_from_cart,5836522,1487580013522845895,NaN,nagaraku,0.40,429681830,49e8d843-adf3-428b-a2c3-fe8bc6a307c9
174,2019-10-01 00:05:35 UTC,remove_from_cart,5677456,1487580008263189483,NaN,estel,10.32,377667011,81326ac6-daa4-4f0a-b488-fd0956a78733
175,2019-10-01 00:05:35 UTC,remove_from_cart,5677456,1487580008263189483,NaN,estel,10.32,377667011,81326ac6-daa4-4f0a-b488-fd0956a78733
190,2019-10-01 00:06:06 UTC,remove_from_cart,5842147,1487580006317032337,NaN,NaN,1.59,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694
192,2019-10-01 00:06:06 UTC,remove_from_cart,5842147,1487580006317032337,NaN,NaN,1.59,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694
213,2019-10-01 00:06:36 UTC,remove_from_cart,5817151,1783999071199952917,NaN,NaN,5.56,464191317,3ab4d9ce-82f9-abc8-ae11-e07eed4987ce
214,2019-10-01 00:06:36 UTC,remove_from_cart,5817151,1783999071199952917,NaN,NaN,5.56,464191317,3ab4d9ce-82f9-abc8-ae11-e07eed4987ce
215,2019-10-01 00:06:42 UTC,remove_from_cart,5698989,1487580006317032337,NaN,NaN,1.27,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694
217,2019-10-01 00:06:42 UTC,remove_from_cart,5698989,1487580006317032337,NaN,NaN,1.27,385985999,d30965e8-1101-44ab-b45d-cc1bb9fae694

# Column sampled values

In [49]:
for col in df.columns:
    print(col + ':', df.loc[df[col].notna(), col].sample(10).values)
    print('')

event_time: ['2019-11-05 14:32:49 UTC' '2019-11-28 10:11:02 UTC'
 '2020-01-31 22:54:33 UTC' '2019-11-17 11:18:24 UTC'
 '2019-10-31 06:15:42 UTC' '2019-11-20 17:20:26 UTC'
 '2020-02-12 19:49:32 UTC' '2019-12-24 10:00:30 UTC'
 '2019-11-27 10:41:07 UTC' '2020-01-07 20:20:25 UTC']

event_type: ['remove_from_cart' 'remove_from_cart' 'view' 'view' 'view'
 'remove_from_cart' 'cart' 'purchase' 'view' 'view']

product_id: [5813864 5826000 5877029 5820752 5769910 5836506 5561008 5819246 5649726
 5649206]

category_id: [1487580009076883471 1487580005092295511 1487580013212467384
 1487580005092295511 1783999067156644376 1487580005855658874
 1487580013858390233 1487580006317032337 1487580005427839846
 1487580005268456287]

category_code: ['appliances.environment.vacuum' 'furniture.living_room.cabinet'
 'appliances.environment.vacuum' 'furniture.bathroom.bath'
 'furniture.living_room.cabinet' 'appliances.environment.vacuum'
 'stationery.cartrige' 'furniture.living_room.cabinet'
 'stationery.cartrige' 'appliances.environment.vacuum']

brand: ['italwax' 'runail' 'irisk' 'farmstay' 'concept' 'lovely' 'farmstay'
 'bpw.style' 'bpw.style' 'irisk']

price: [1.98 5.71 5.24 5.56 5.54 0.95 1.27 1.94 5.24 5.86]

user_id: [466360388 526048273 539370875 562601590 494013138 499375108 420609309
 561003511 551557496 555109983]

user_session: ['0e18add3-0d5b-4b87-ae76-88518e5a22f9'
 '6e028f4e-c788-49cc-8e68-6a890c2c7959'
 '7e4babe8-1e52-4f1f-afc4-23a604d39411'
 'f7acb785-bddf-4dc4-a617-ae251f41fa7f'
 '7425d7c8-efe1-4bac-9495-a2f0726b555f'
 '56c05e29-b6d3-4e35-b86e-d989ca958576'
 '94e18845-7b19-4163-822e-a41fef47e64d'
 '351e20a8-9442-4e28-b23c-9e399a25ee05'
 '172a9aba-562c-42ce-8439-99275315c4c0'
 '42dceff9-c10a-4565-aa33-5bbe4c452435']

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20692840 entries, 0 to 4156681
Data columns (total 9 columns):
 #   Column         Dtype
---  ------         -----
 0   event_time     object
 1   event_type     object
 2   product_id     int64
 3   category_id    int64
 4   category_code  object
 5   brand          object
 6   price          float64
 7   user_id        int64
 8   user_session   object
dtypes: float64(1), int64(3), object(5)
memory usage: 1.5+ GB

In [15]:
for col in df.columns:
    print(col+":", np.max(df[col].map(lambda x: len(str(x)))))

event_time: 23
event_type: 16
product_id: 7
category_id: 19
category_code: 38
brand: 13
price: 6
user_id: 9
user_session: 36