In [1]:
import pandas as pd
from sqlalchemy import text
from sqlalchemy import create_engine
from pathlib import Path
import pandas as pd
import numpy as np
import re
import os

import plotly.express as px
import plotly.graph_objects as go

function for extracting data from mysql database.

In [3]:
def extract_queries(sql_content: str) -> dict:
    '''
    从 SQL 文件内容中提取所有 -- name: xxx 标记的查询
    '''
    queries = {}
    current_name = None
    current_lines = []

    for line in sql_content.splitlines():
        # matching pattern: `-- name:`  (allow blanks at the front and end)
        match = re.match(r'^\s*--\s*name:\s*(.+?)\s*$', line, re.IGNORECASE)
        
        if match:
            # save previous one matching query 
            if current_name is not None:
                queries[current_name] = '\n'.join(current_lines).strip()
            # setup for matching query
            current_name = match.group(1).strip() # split '-- name: ...'
            current_lines = []
        else:
            if current_name is not None:
                current_lines.append(line)

    # save the last query
    if current_name is not None:
        queries[current_name] = '\n'.join(current_lines).strip()

    return queries


def query_from_file(sql_path, query_name, database_name):
    '''
    sql path: sql file path
    query_name: the part after '-- name:'
    database_name: mysql database name
    return pd df
    '''
    engine = create_engine(f'mysql+pymysql://root:Fu2002219219@localhost:3306/{database_name}')
    
    content = Path(sql_path).read_text(encoding='utf-8')
    queries = extract_queries(content)

    if query_name not in queries.keys():
        raise ValueError(f"{query_name} does not exist, avaliable queries: {list(queries.keys())}")

    else:
        sql = pd.read_sql(text(queries[query_name]), engine)


    return sql

In [3]:
parent_dir = os.path.dirname(os.getcwd())
monthly_rev = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                'month revenue',
                'cosmetics_shop_data'
)

monthly_rev['year'] = np.where(monthly_rev['month'] >= 10, 2019, 2020)
monthly_rev['month'] = monthly_rev['year'].astype(str) + '-' + monthly_rev['month'].astype(str)


fig = px.line(data_frame=monthly_rev, x='month', y='total_revenue')
fig.update_xaxes(type = 'category')
fig.update_layout(template = 'plotly_white', xaxis_title = 'Month', yaxis_title = 'Monthly Revenue', title = 'Monthly Total Revenue')

In [4]:
monthly_active_user = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                'view + cart + purchase active user',
                'cosmetics_shop_data'
)

monthly_active_user['month'] = monthly_active_user['year'].astype(str) + '-' + monthly_active_user['month'].astype(str)

fig_1 = px.line(data_frame=monthly_active_user, x='month', y='num_active_users', color = 'type')
fig_1.update_xaxes(type = 'category')
fig_1.update_layout(template = 'plotly_white', xaxis_title = 'Month', yaxis_title = 'Monthly active user', legend_title_text ='Action type', title = 'Active User (view + cart + purchase )')

In [5]:
df = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                '11 vs. 1 revenue mom',
                'cosmetics_shop_data'
)
print(df['mom'].values[0] + ' revenue MoM: ', np.round(df['value'].values[0], 2), '%')

Nov/19 vs. Jan/20 revenue MoM:  15.87 %

In [6]:
df = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                '11 vs. 1 active user',
                'cosmetics_shop_data'
)
print(df['mom'].values[0] + ' active user (view) MoM: ', np.round(df['value'].values[0], 2), '%')

Nov/19 vs. Jan/20 active user (view) MoM:  -10.59 %

Question/Problem:

**For the 2 highest revenue months within these 5 months, why does November that has 10.59% lower users that viewed products on the platform have 15.87% higher total revenue than January, what are the potential causes?**

1. according to 
    $$
    \text{Revenue} = T_{\text{user that viewed}} \times \text{conversion rate}_{\text{view} \rightarrow \text{purchase}} \times \text{items/user} \times \text{value/item}
    $$  

    which components led to the problem?

    conversion rate (both *view $\rightarrow$ cart* and *cart $\rightarrow$ purchase*) primary, transaction/user secondary

2. hypothesis for causing components:
    - conversion rate:

        - Nov's userbase was in a significant difference from Jan's userbase. The shop platform in Nov. attracted more new users that had better quality (stronger purchasing power/will) than Jan., possibly because of promotional event (e.g. black friday). While Jan's userbase backed to normal state, where majority of the users are regular users.
        - Nov's userbase structure partially changed compared to Jan's userbase, where new users and old users are mixing, the overall structure was leaning towards the new users, which led to revenue rise.
        - Nov's userbase was generally similar to Jan's userbase. The revenue difference was made by the structure shifting of the platform's products from Nov. to Jan.

    - items/user:
        - Nov's userbase structure shifted to new users who would buy more items in a month, while Jan's userbase backed to normal userbase.
        
        - Nov's userbase was generally simialr to Jan's, however, the users in Nov. showed a stronger purchasing pattern.

        - The products on the platform were in promotion (e.g. black friday), which led to a higher number of items bought per user, while Jan's products backed to normal price.

In [8]:
df = pd.concat([
    query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                '11 metrics',
                'cosmetics_shop_data'
),
    query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                '1 metrics',
                'cosmetics_shop_data'
)
], axis=0)

df = pd.concat([df, 
           pd.DataFrame(['11 vs. 1 mom'] + (df.iloc[0, 1:] / df.iloc[1, 1:] - 1).to_list(), 
                        index=['month', 'total_users', 'crt', 'items_user', 'avg_item_value']).transpose(),
           pd.DataFrame(['11 vs. 1 ratio'] + (df.iloc[0, 1:] / df.iloc[1, 1:]).to_list(), 
                                   index=['month', 'total_users', 'crt', 'items_user', 'avg_item_value']).transpose()
           ], axis=0, ignore_index= True)
df

            month total_users       crt items_user avg_item_value
0              11      355643    0.0886     10.223       4.748712
1               1      397775    0.0709     9.3411       5.010261
2    11 vs. 1 mom   -0.105919  0.249647   0.094411      -0.052203
3  11 vs. 1 ratio    0.894081  1.249647   1.094411       0.947797

In [95]:
df = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                '11: view cart remove_from_cart purchase',
                'cosmetics_shop_data'
)
df['month'] = 11

df_1 = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                '1: view cart remove_from_cart purchase',
                'cosmetics_shop_data'
)
df_1['month'] = 1

df = pd.concat([
    df, df_1
], axis =0, ignore_index=True)
df

       type  num_users  last_type_users      crt  month
0      view     355643              NaN      NaN     11
1      cart      95939         355643.0  26.9762     11
2  purchase      31524          95939.0  32.8584     11
3      view     397775              NaN      NaN      1
4      cart      92653         397775.0  23.2928      1
5  purchase      28220          92653.0  30.4577      1

In [ ]:
df = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                'find collapsed user (1 month diff)',
                'cosmetics_shop_data'
)

In [ ]:
df['retained_user_rate(%)'] = df['collapsed_user'] * 100 /  df['current_month_view_user']
df

,months,previous_month_view_user,current_month_view_user,collapsed_user,retained_user_rate
0,10 vs. 11,388331,355643,50965,14.330382
1,11 vs. 12,355643,358212,52907,14.769745
2,1 vs. 12,358212,397775,51002,12.821821
3,2 vs. 1,397775,379246,60034,15.829831

In [6]:
parent_dir = os.path.dirname(os.getcwd())
df_1 = query_from_file(f'{parent_dir}/sql_scripts/explore.sql',
                'find collapsed user (cumulate month diff, optimized)',
                'cosmetics_shop_data'
)

In [8]:
df_1['retained_user_rate(%)'] = df_1['collapsed_user'] * 100 /  df_1['current_month_view_user']
df_1

,months,previous_month_view_user,current_month_view_user,collapsed_user,retained_user_rate(%)
0,2019-10 vs. 2019-11,388331,355643,50965.0,14.330382
1,2019-11 vs. 2019-12,355643,358212,66261.0,18.497705
2,2019-12 vs. 2020-01,358212,397775,76420.0,19.211866
3,2020-01 vs. 2020-02,397775,379246,87807.0,23.153046